PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX erl: <http://erlangen-crm.org/current/> 

SELECT ?subject ?predicate ?object ?type ?label 
WHERE {
  ?subject ?predicate ?object .
  
  OPTIONAL {
    ?subject a ?type .
  }
  OPTIONAL {
    ?subject rdfs:label ?label .
  }

  FILTER (?type != erl:E55_Type)
  FILTER (?object != erl:E55_Type)
  FILTER (?object NOT IN (?type))
  FILTER (?subject NOT IN (?type))
  FILTER (?predicate NOT IN (erl:P3_has_note, rdfs:label))
}




