PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX erl: <http://erlangen-crm.org/current/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


SELECT ?subject ?predicate ?object
WHERE {
  ?subject ?predicate ?object
  FILTER (?predicate NOT IN ( rdf:type, rdfs:label))
  FILTER (!isLiteral(?object ))
}