PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX erl: <http://erlangen-crm.org/current/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  DISTINCT ?subject ?info
WHERE {
  ?subject ?predicate ?object .
  OPTIONAL {?subject ?predicate ?info .}
  FILTER (?subject NOT IN (?predicate))
  FILTER (isLiteral(?object ))

}
